### ISSUE TITLE
"AuthenticationFailed" Error in Dashboard when connecting to /api/management/

### ISSUE THREAD

**Issue by smartin314** [Mobility-Data-Space/mobility-data-space#32]
We have a MDS EDC Connector running on our Server gaiax.example.de

Our UI-Dashboard is available at https://gaiax.example.de/dashboard and when it requests data from the Management-API (https://gaiax.example.de/api/management/) we always get the following Error-Message:
`[{"message":"Request could not be authenticated","type":"AuthenticationFailed","path":null,"invalidValue":null}]`

This happens for every request to the Management-API, for example https://gaiax.example.de/api/management/edc-ui-config or https://gaiax.example.de/api/management/last-commit-info

We set up our Connector using this template: https://github.com/Mobility-Data-Space/mobility-data-space/blob/main/templates/connector_with_traefik.yaml . Because Traefik couldn't get a certificate to authenticate, we created one by ourselves and added it to traefik:
```
traefik:
    image: "traefik:v2.11"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configuration/:/configuration/"
```
When we try to access the Management-API using curl with the API-KEY we get the same Error-Message.
